fila = []
print('Fila vazia:',fila)
fila.append('João')
print('Chegou João:',fila)
fila.extend(['Pedro','Paulo'])
print('Chegaram Pedro e Paulo:',fila)
fila.pop(0)
print('João foi atendido:',fila)
fila.append('Maria')
print('Chegou Maria:',fila)
fila.append('Alice')
print('Chegou Alice:',fila)
fila.append('Joana')
print('Chegou Joana:',fila)
fila.pop()
print('Joana desistiu:', fila)
fila.pop(2)
print('Maria também desistiu:',fila)

